/**
 * 翻译字典模块
 * 
 * safeGlobalDict:  安全长句字典，不会与代码变量冲突，可直接全局替换
 * riskyShortWords: 危险短词字典，只能在 UI 属性上下文中替换，否则会导致白屏
 */

const safeGlobalDict = {
    "Manage Account": "管理账号",
    "Manage your account and billing": "管理您的账号与账单",
    "Invite Team Members": "邀请团队成员",
    "Accelerate development, shared knowledge, and context across your team": "跨团队加速开发并共享知识与上下文",
    "Preferences": "偏好设置",
    "Sync layouts across windows": "跨窗口同步布局",
    "When enabled, all windows share the same layout": "启用后，所有窗口共享相同的布局",
    "Editor Settings": "编辑器设置",
    "Configure font, formatting, minimap and more": "配置字体、格式化、缩略图等",
    "Keyboard Shortcuts": "键盘快捷键",
    "Configure keyboard shortcuts": "配置键盘快捷键",
    "Import Settings from VS Code": "从 VS Code 导入设置",
    "Import settings, extensions, and keybindings from VS Code": "导入 VS Code 的设置、扩展和快捷键绑定",
    "See warnings and tips that you've hidden": "查看您已隐藏的警告和提示",
    "Layout": "布局",
    "Status Bar": "状态栏",
    "Show status bar": "显示状态栏",
    "Auto-hide editor when empty": "空闲时自动隐藏编辑器",
    "When all editors are closed, hide the editor area and maximize chat": "关闭所有编辑器时，隐藏编辑器并最大化聊天窗口",
    "Notifications": "通知",
    "System Notifications": "系统通知",
    "Show system notifications when Agent completes or needs attention": "智能体完成任务或需要注意时显示系统通知",
    "System Tray Icon": "系统托盘图标",
    "Show Cursor in system tray": "在系统托盘显示 Cursor",
    "Completion Sound": "完成提示音",
    "Play a sound when Agent finishes responding": "智能体完成响应时播放提示音",
    "Privacy": "隐私",
    "Rules, Skills, Subagents": "规则、技能与子智能体",
    "Tools & MCP": "工具与 MCP",
    "Tools & MCPs": "工具与 MCP",
    "Indexing & Docs": "索引与文档",
    "Cloud Agents": "云端智能体",
    "Team Plan": "团队版",
    "Search settings": "搜索设置",
    "Auto-Run Mode": "自动运行模式",
    "Choose how Agent runs tools like command execution, MCP, and file writes.": "选择智能体如何运行命令执行、MCP 和文件写入等工具。",
    "Command Allowlist": "命令白名单",
    "Commands that can run automatically": "可自动运行的命令",
    "MCP Allowlist": "MCP 白名单",
    "MCP tools that can run automatically. Format: 'server:tool', 'server:*' for all tools from a server, '*:tool' for a tool from any server, or *:* for all tools from all servers": "可自动运行的 MCP 工具。格式：'server:tool'、'server:*' 表示某服务器的全部工具、'*:tool' 表示任意服务器的某工具、*:* 表示所有服务器的所有工具",
    "Fetch Domain Allowlist": "请求域名白名单",
    "Domains that Agent can fetch from automatically. Use '*' for all domains, '*.example.com' for wildcard subdomains.": "智能体可自动请求的域名。使用 '*' 匹配所有域名，'*.example.com' 匹配通配符子域名。",
    "Auto-Approved Mode Transitions": "自动批准的模式切换",
    "Mode transitions that will be automatically approved without prompting.": "无需提示即自动批准的模式切换。",
    "Browser Protection": "浏览器保护",
    "Prevent Agent from automatically running Browser tools": "阻止智能体自动运行浏览器工具",
    "MCP Tools Protection": "MCP 工具保护",
    "Prevent Agent from automatically running MCP tools": "阻止智能体自动运行 MCP 工具",
    "File-Deletion Protection": "文件删除保护",
    "Prevent Agent from deleting files automatically": "阻止智能体自动删除文件",
    "External-File Protection": "外部文件保护",
    "Prevent Agent from creating or modifying files outside of the workspace automatically": "阻止智能体自动创建或修改工作区外的文件",
    "Default Location": "默认位置",
    "Where to open new agents": "新智能体的打开位置",
    "Text Size": "文字大小",
    "Adjust the conversation text size": "调整对话文字大小",
    "Ask Every Time": "每次询问",
    "Use Allowlist": "使用白名单",
    "Run Everything": "运行所有",
    "Settings": "设置",
    "Extra Large": "超大",
    "Cursor Tab": "Cursor Tab 补全",
    "Context-aware, multi-line suggestions around your cursor based on recent edits": "基于最近编辑，在光标周围提供上下文感知的多行建议",
    "Partial Accepts": "部分接受",
    "Accept the next word of a suggestion via Ctrl+RightArrow": "通过 Ctrl+右箭头接受建议的下一个单词",
    "Suggestions While Commenting": "注释时建议",
    "Allow Tab to trigger while in a comment region": "允许在注释区域中触发 Tab 补全",
    "Whitespace-Only Suggestions": "仅空白建议",
    "Suggest edits like new lines and indentation that modify whitespace only": "仅建议修改空白的编辑，如换行和缩进",
    "Automatically import necessary modules for TypeScript": "自动导入 TypeScript 所需的模块",
    "Auto Import for Python": "Python 自动导入",
    "Enable auto import for Python. This is a beta feature.": "启用 Python 自动导入。这是一个测试功能。",
    "Provide domain-specific knowledge and workflows for the agent": "为智能体提供特定领域的知识和工作流",
    "Include third-party Plugins, Skills, and other configs": "包含第三方插件、技能和其他配置",
    "Automatically import agent configs from other tools": "自动从其他工具导入智能体配置",
    "Use Rules to guide agent behavior, like enforcing best practices or coding standards. Rules can be applied always, by file path, or manually.": "使用规则引导智能体行为，例如强制执行最佳实践或编码标准。规则可以始终应用、按文件路径应用或手动应用。",
    "Skills are specialized capabilities that help the agent accomplish specific tasks. Skills will be invoked by the agent when relevant or can be triggered manually with / in chat.": "技能是帮助智能体完成特定任务的专业能力。智能体会在相关时自动调用技能，也可在聊天中通过 / 手动触发。",
    "No Skills Yet": "暂无技能",
    "Skills help the agent accomplish specific tasks": "技能帮助智能体完成特定任务",
    "New Skill": "新建技能",
    "Create specialized agents for complex tasks. Subagents can be invoked by the agent to handle focused work in parallel.": "创建用于复杂任务的专业智能体。子智能体可被主智能体调用，以并行处理专项工作。",
    "No Subagents Yet": "暂无子智能体",
    "Create specialized agents to handle focused tasks": "创建专业智能体来处理专项任务",
    "New Subagent": "新建子智能体",
    "Create reusable workflows triggered with / prefix in chat. Use commands to standardize processes and make common tasks more efficient.": "创建在聊天中通过 / 前缀触发的可复用工作流。使用命令标准化流程，提高常见任务的效率。",
    "No Commands Yet": "暂无命令",
    "Create commands to build reusable workflows": "创建命令以构建可复用工作流",
    "New Command": "新建命令",
    "+ New": "+ 新建",

    // ── 智能体设置 ──
    "Auto-Clear Chat": "自动清除聊天",
    "After periods of inactivity, open the Agent Pane to a new conversation": "一段时间不活动后，将智能体面板打开为新对话",
    "Submit with Ctrl + Enter": "使用 Ctrl + Enter 提交",
    "When enabled, Ctrl + Enter submits chat and Enter inserts a newline": "启用后，Ctrl + Enter 提交聊天，Enter 插入换行",
    "Max Tab Count": "最大标签页数",
    "Limit how many chat tabs can be open at once": "限制同时打开的聊天标签页数量",
    "Queue Messages": "消息队列",
    "Adjust the default behavior of sending a message while Agent is running": "调整智能体运行时发送消息的默认行为",
    "Send after current message": "当前消息后发送",
    "Stop & send right away": "立即停止并发送",
    "Usage Summary": "用量摘要",
    "When to show the usage summary at the bottom of the chat pane": "何时在聊天面板底部显示用量摘要",
    "Agent Autocomplete": "智能体自动补全",
    "Contextual suggestions while prompting Agent": "向智能体提问时提供上下文建议",

    // ── Agent Review ──
    "Start Agent Review on Commit": "代码提交时启动智能体审查",
    "Automatically review your changes for issues after each commit": "在每次提交后自动审查您的更改是否存在问题",
    "Include Submodules in Agent Review": "在智能体审查中包含子模块",
    "Include changes from Git submodules in the review": "在审查中包含 Git 子模块的更改",
    "Include Untracked Files in Agent Review": "在审查中包含未跟踪文件",
    "Include untracked files (new files not yet added to Git) in the review": "在审查中包含未跟踪文件（尚未添加到 Git 的新文件）",
    "Default Approach": "默认方式",
    "Choose between quick or more thorough, higher-cost analysis": "选择快速或更彻底、成本更高的分析",

    // ── Context & Applied Changes ──
    "Web Search Tool": "网络搜索工具",
    "Allow Agent to search the web for relevant information": "允许智能体在网络上搜索相关信息",
    "Auto-Accept Web Search": "自动接受网络搜索",
    "Skip approval dialog; Agent may run web searches automatically": "跳过批准对话；智能体可自动运行网络搜索",
    "Web Fetch Tool": "网页获取工具",
    "Allow Agent to fetch content from URLs": "允许智能体从 URL 获取内容",
    "Hierarchical Cursor Ignore": "分层 Cursor 忽略",
    "Apply .cursorignore files to all subdirectories. Changing this setting will require a restart of Cursor.": "将 .cursorignore 文件应用到所有子目录。更改此设置需要重启 Cursor。",
    "Ignore Symlinks in Cursor Ignore Search": "在 Cursor 忽略搜索中忽略符号链接",
    "Use with caution. Skip symlinks during .cursorignore file discovery. Only enable if your repository has many symlinks and all .cursorignore files are reachable without them. Changing this setting will require a restart of Cursor.": "谨慎使用。在发现 .cursorignore 文件时跳过符号链接。仅当您的仓库存有许多符号链接，且没有符号链接也能访问所有 .cursorignore 文件时才启用。更改此设置需要重启 Cursor。",
    "Applying Changes": "应用更改",
    "Inline Diffs": "内联差异",
    "Show inline diff decorations in the editor instead of only showing changes in the review panel": "在编辑器中显示内联差异装饰，而不是仅在审查面板中显示更改",
    "Jump to Next Diff on Accept": "接受时跳转到下一个差异",
    "Automatically jump to the next diff when accepting changes with Ctrl+Y": "使用 Ctrl+Y 接受更改时自动跳转到下一个差异",
    "Auto Format on Agent Finish": "智能体完成时自动格式化",
    "Automatically format files when the agent finishes": "智能体完成任务时自动格式化文件",

    // ── Inline Editing & Terminal ──
    "Inline Editing & Terminal": "内联编辑与终端",
    "Legacy Terminal Tool": "旧版终端工具",
    "Use the legacy terminal tool in agent mode, for use on systems with unsupported shell configurations": "在智能体模式下使用旧版终端工具，适用于 shell 配置不受支持的系统",
    "Toolbar on Selection": "选中时显示工具栏",
    "Show Add to Chat & Quick Edit buttons when selecting code": "选择代码时显示“添加到聊天”和“快速编辑”按钮",
    "Auto-Parse Links": "自动解析链接",
    "Automatically parse links when pasted into Quick Edit (Ctrl+K) input": "粘贴到快速编辑 (Ctrl+K) 输入框时自动解析链接",
    "Themed Diff Backgrounds": "主题差异背景",
    "Use themed background colors for inline code diffs": "为内联代码差异使用主题背景色",
    "Terminal Hint": "终端提示",
    "Show a hint for Ctrl+K in the Terminal": "在终端中显示 Ctrl+K 提示",
    "Preview Box for Terminal Ctrl+K": "终端 Ctrl+K 的预览框",
    "Use a preview box instead of streaming responses directly into the shell": "使用预览框而不是将响应直接流式传输到 shell 中",
    "Collapse Auto-Run Commands": "折叠自动运行命令",
    "Collapse auto-run command output by default in Terminal command previews": "在终端命令预览中默认折叠自动运行的命令输出",

    // ── Voice Mode & Attribution ──
    "Voice Mode": "语音模式",
    "Submit Keywords": "提交关键字",
    "Custom keywords that trigger auto-submit in voice mode. Only single words (no spaces) are allowed. Punctuation and capitalization are ignored.": "在语音模式下触发自动提交的自定义关键字。仅允许单个单词（无空格）。忽略标点符号和大小写。",
    "Attribution": "代码署名",
    "Commit Attribution": "提交署名",
    "Mark Agent commits as 'Made with Cursor'": "将智能体提交标记为 'Made with Cursor'",
    "PR Attribution": "PR 署名",
    "Mark pull requests as made with Cursor": "将拉取请求标记为使用 Cursor 制作",

    // ── Privacy ──
    "Privacy Mode": "隐私模式",
    "Your code data will not be trained on or used to improve the product. Code may be stored to provide features such as Background Agent.": "您的代码数据不会被用于训练或改进产品。代码可能会被存储以提供后台智能体等功能。",
    "Data Sharing is controlled by the team admin. Configure here.": "数据共享由团队管理员控制。在此配置。",

    // ── Miscellaneous ──
    "Accept the next word of a suggestion via Ctrl+RightArrow": "通过 Ctrl+RightArrow 接受建议的下一个词",
    "Automatically import necessary modules for TypeScript": "自动为 TypeScript 导入必要的模块",

    // ── Usage Limits ──
    "Increase limits for faster responses": "提高限制以获得更快的响应",
    "You're over your current usage limit and your requests are being processed with Auto in the slow queue.": "您已超出当前配置的使用量限制，您的请求正以临时排队方式在慢速队列中处理。",
    "Set new limit": "设置新限制",

    // ── Cloud / Background Agents ──
    "Cloud Agents require a Git repository in an open folder.": "云智能体需要打开的文件夹中包含 Git 仓库。",
    "Open a Git repository": "打开 Git 仓库",
    "Background agents only work in folders with a git repository.": "后台智能体仅在包含 git 仓库的文件夹中工作。",
    "Please open a folder that contains a git repository to use this feature.": "请打开包含 git 仓库的文件夹以使用此功能。",

    // ── Extensions / Marketplace ──
    "Extend Cursor with Skills, Rules, Agents, Hooks, and MCPs": "使用技能、规则、智能体、钩子和 MCP 扩展 Cursor",

    // ── Network ──
    "HTTP Compatibility Mode": "HTTP 兼容模式",
    "HTTP/2 is recommended for low-latency streaming. In some corporate proxy and VPN environments, the compatibility mode may need to be lowered.": "推荐使用 HTTP/2 以实现低延迟流式传输。在某些企业代理和 VPN 环境中，可能需要降低兼容模式。",
    "Required Domains": "必需的域名",
    "These domains must be accessible for Cursor to function. Add them to your firewall or proxy allowlist.": "必须可访问这些域名，Cursor 才能正常工作。请将它们添加到您的防火墙或代理白名单中。",
    "Network Diagnostics": "网络诊断",
    "Check network connectivity to all Cursor services": "检查与所有 Cursor 服务的网络连接",

    // ── Update ──
    "Update Access": "更新通道",
    "By default, get notifications for stable updates. In Early Access, pre-release builds may be unstable for production work.": "默认情况下，接收稳定版更新的通知。在抢先体验通道中，预发布版本可能不稳定，不建议用于生产环境。",
    "Extension RPC Tracer": "扩展 RPC 追踪器",
    "Log extension host RPC messages to JSON files viewable in Perfetto for performance analysis. Requires a restart to take effect.": "将扩展主机的 RPC 消息记录到 JSON 文件中，可在 Perfetto 中查看以进行性能分析。需要重启才能生效。",

    // ── Hooks ──
    "Hooks let you run custom scripts at specific points during the agent's execution to modify behavior, enforce policies, or add custom logging.": "钩子允许您在智能体执行的特定点运行自定义脚本，以修改行为、强制执行策略或添加自定义日志。",
    "No hooks configured": "未配置钩子",
    "No hook executions yet": "暂无钩子执行记录",

    // ── Tools / Browser ──
    "Browser Automation": "浏览器自动化",
    "Browser automation disabled": "浏览器自动化已禁用",
    "Show Localhost Links in Browser": "在浏览器中显示 Localhost 链接",
    "Automatically open localhost links in the Browser Tab": "自动在浏览器标签页中打开 localhost 链接",

    // ── Features / Documentation Links ──
    "Learn about Rules": "了解规则",
    "Learn about Skills": "了解技能",
    "Learn about Subagents": "了解子智能体",
    "Learn about Commands": "了解命令",
    "User Rule": "用户规则",
    "Project Rule": "项目规则",
    "Add from GitHub/GitLab": "从 GitHub/GitLab 添加",

    // ── Commands & MCP ──
    "Project Command": "项目命令",
    "User Command": "用户命令",
    "New MCP Server": "新建 MCP 服务器",
    "Add a Custom MCP Server": "添加自定义 MCP 服务器",

    // ── Models ──
    "Balanced quality and speed, recommended for most tasks": "平衡质量和速度，推荐用于大多数任务",
    "Multiple models require a Git repository.": "使用多模型功能需要 Git 仓库。",

    // ── Dialogs ──
    "Are you sure? This replaces your settings and extensions with your vscode ones. This cannot be undone.": "确定要继续吗？这将用您的 VS Code 设置和扩展替换当前的设置和扩展。此操作无法撤销。",
    "Reset \"Don't Ask Again\" Dialogs": "重置“不再询问”弹窗",
    "Reset \"Don’t Ask Again\" Dialogs": "重置“不再询问”弹窗",
    "See warnings and tips that you've hidden": "查看您已隐藏的警告和提示",
    "See warnings and tips that you’ve hidden": "查看您已隐藏的警告和提示",
    "No Hidden Dialogs Yet": "暂无隐藏的弹窗",
    "You haven't marked any dialogs as \"Don't ask again\". Any hidden dialogs will appear here to manage.": "您尚未将任何弹窗标记为“不再询问”。任何隐藏的弹窗都将显示在此处以供管理。",
    "You haven’t marked any dialogs as \"Don’t ask again\". Any hidden dialogs will appear here to manage.": "您尚未将任何弹窗标记为“不再询问”。任何隐藏的弹窗都将显示在此处以供管理。",

    // ── 下面原本误放入了短词字典 ──
    "Submit with ": "使用 ",
    "When enabled, ": "启用后，",
    " submits chat and ": " 提交聊天，",
    " inserts a newline": " 插入换行",
    "Accept the next word of a suggestion via ": "使用 ",
    " accept the next word of a suggestion": " 接受建议的下一个词",
    "Automatically import necessary modules for TypeScript": "自动为 TypeScript 导入必要的模块",

    // Codebase 相关设置
    "Codebase": "代码库",
    "Codebase Indexing": "代码库索引",
    "Delete Index": "删除索引",
    "Index New Folders": "索引新文件夹",
    "Automatically index any new folders with fewer than 250,000 files": "自动索引少于 250,000 个文件的新文件夹",
    "View included files.": "查看已包含的文件。",
    "Team-Level Repository Control": "团队级代码库控制",
    "Disable AI features in specific repositories based on file pattern": "基于文件匹配模式在特定代码库中禁用 AI 功能",
    "Index Repositories for Instant Grep": "为 Instant Grep 索引代码库",
    "Automatically index repositories to speed up Grep searches. All data is stored locally.": "自动索引代码库以加速 Grep 搜索。所有数据均存储在本地。",
    "Crawl and index custom resources and developer docs": "爬取并索引自定义资源和开发者文档",
    "No Docs Added": "未添加文档",
    "Add Doc": "添加文档",
    "Increase limits for faster responses": "提升额度以获取更快响应",
    "Automatically jump to the next diff when accepting changes with ": "当接受更改时，自动跳转到下一个差异，借助 ",
    "Ignore Files in ": "忽略包含在 ",
    "Ignore Files in .cursorignore": "忽略 .cursorignore 中的文件",
    "Nightly Updates Apply Automatically": "每夜更新自动应用",
    "Learn about codebase indexing": "了解代码库索引",
    "Embed codebase for improved contextual understanding and knowledge. Embeddings and metadata are stored in the": "嵌入代码库以增强上下文理解和知识。嵌入向量和元数据存储在",
    ", but all code is stored locally.": "，但所有代码都存储在本地。",
    "Agent Review": "智能体审查",
    "Data Sharing is controlled by ": "数据共享由",
    "team admin.": "团队管理员控制。",
    "Nightly builds will silently download and install updates without prompting you.": "每夜版本将静默下载并安装更新，不会提示您。",
    "Keybinding: editor.action.inlineSuggest.acceptNextWord": "快捷键: editor.action.inlineSuggest.acceptNextWord",
    "Keybinding: ": "快捷键: ",
    "Keybinding:": "快捷键:",

    // ── 聊天 & 智能体界面 ──
    "Start New Chat": "开始新对话",
    "Fork Chat": "分支对话",
    "Replace Chat": "替换对话",
    "Replace current chat?": "替换当前对话？",

    "Rename Chat": "重命名对话",
    "Start New Chat?": "开始新对话？",
    "Export Transcript": "导出对话记录",
    "Export Chat": "导出对话",
    "Export Chat (Developer)": "导出对话（开发者格式）",
    "Import Chat": "导入对话",
    "Share Transcript": "分享对话记录",
    "Archive Prior Chats": "归档历史对话",
    "Archive all chats older than this one": "归档比此更早的所有对话",
    "Clear History": "清除历史",
    "Clear Conversation History": "清除对话历史",
    "Summarize the conversation": "总结对话",
    "Conversation Corrupted": "对话已损坏",
    "Conversation Too Long": "对话过长",
    "Submit from a previous message?": "从之前的消息提交？",
    "Multiple Messages": "多条消息",
    "Loading chat...": "加载对话中...",
    "This chat could not be loaded.": "无法加载此对话。",
    "Needs Attention": "需要关注",
    "Taking a little while...": "稍等一下...",
    "Chat Too Old": "对话已过期",

    "Close Other Chats": "关闭其他对话",
    "No results": "无结果",
    "No results found": "未找到结果",
    "No changed files": "无更改的文件",
    "Scroll to bottom": "滚动到底部",
    "Conversation Density": "对话密度",
    "Choose how much detail Agent tool calls show in the conversation": "选择智能体工具调用在对话中显示的详细程度",
    "Queue Messages": "消息排队",
    "Adjust the default behavior of sending a message while Agent is streaming": "调整智能体流式响应时发送消息的默认行为",
    "Pasted Link": "已粘贴链接",

    // ── 智能体操作 ──
    
    "Build in New Agent": "在新智能体中构建",
    "Build in Parallel": "并行构建",
    "Add an agent to get started": "添加一个智能体以开始",
    "Add agents, context, tools...": "添加智能体、上下文、工具...",
    "Add a to-do to get started": "添加待办事项以开始",
    "Run and coordinate multiple tasks in parallel": "并行运行和协调多个任务",
    "Find with Agent": "使用智能体查找",
    "Ask Agent": "询问智能体",
    "Ask Cursor questions about your codebase": "向 Cursor 提问关于代码库的问题",
    "View Plan": "查看计划",
    "Find in Plan": "在计划中查找",
    "Save to Workspace": "保存到工作区",
    "Agent Edit": "智能体编辑",
    "Agent Layout": "智能体布局",
    "Agent Settings": "智能体设置",
    "Agent decides when to apply": "智能体决定何时应用",
    "Agent disconnected": "智能体已断开连接",
    "Agent encountered an error": "智能体遇到错误",
    "Agent Requires Login": "智能体需要登录",
    "No agents yet": "暂无智能体",
    "No recent agents": "暂无最近使用的智能体",
    "The agent's machine may not be running. Send a message to restart.": "智能体的机器可能未运行。发送消息以重启。",

    // ── 云端智能体 ──
    
    "Failed to start Cloud Agent": "云端智能体启动失败",
    "Retry cloud agent request": "重试云端智能体请求",
    "Cloud Desktop": "云端桌面",
    "Cloud Desktop unavailable": "云端桌面不可用",
    "Cloud Agents Not Supported in Privacy Mode (Legacy)": "隐私模式（旧版）不支持云端智能体",
    "Open Virtual Machine": "打开虚拟机",
    "Cloud MCP Servers": "云端 MCP 服务器",
    "Servers available to cloud agents.": "云端智能体可用的服务器。",
    "Team MCP Servers": "团队 MCP 服务器",
    "Configure MCP servers in the dashboard to make them available in Cursor on desktop and in the cloud.": "在仪表板中配置 MCP 服务器，使其在桌面端和云端可用。",
    "No Team MCP Servers": "暂无团队 MCP 服务器",

    // ── MCP ──
    "Open MCP Settings": "打开 MCP 设置",
    
    "Add MCP": "添加 MCP",
    "Add MCP Server": "添加 MCP 服务器",

    // ── 模型 & MAX ──
    "Search models": "搜索模型",
    "Add Models": "添加模型",
    "Use Multiple Models": "使用多模型",
    "MAX Mode": "MAX 模式",
    "Enable MAX Mode": "启用 MAX 模式",
    "Multiple models require a Git repository.": "使用多模型功能需要 Git 仓库。",

    // ── Git & 源代码管理 ──
    "Create PR": "创建 PR",
    "Create Pull Request": "创建拉取请求",
    "Commit Changes": "提交更改",
    "Commit changes": "提交更改",
    "Stash Changes": "暂存更改",
    "Stash changes": "暂存更改",
    "Save changes to a stash and restore them later": "暂存更改以便稍后恢复",
    "Stashing changes...": "正在暂存更改...",
    "Discard Changes": "丢弃更改",
    "Discard Changes?": "丢弃更改？",
    "Checkout Branch": "切换分支",
    "Permanently discard your current changes before switching branches": "切换分支前永久丢弃当前更改",
    "Cancel the checkout operation": "取消切换操作",
    "Create a checkpoint commit with your current changes": "使用当前更改创建检查点提交",
    "Open Source Control": "打开源代码管理",
    "Review Changes": "审查更改",
    "Refresh Changes": "刷新更改",
    "Refresh Status": "刷新状态",
    "Merge Editor": "合并编辑器",
    "Merge commit": "合并提交",
    "Rebase merge": "变基合并",
    "Merge manually": "手动合并",
    "Git Required": "需要 Git",
    "Score Commit for AI Content": "为 AI 内容评分提交",
    "File renamed without changes": "文件已重命名但无更改",
    "Only whitespace changes": "仅有空白字符更改",
    "Copy Remote URL": "复制远程 URL",
    "Open pull request": "打开拉取请求",
    "Apply to Specific Files & Folders": "应用于特定文件和文件夹",

    // ── 常见操作按钮 ──
    "Reload Window": "重新加载窗口",
    "Continue Anyway": "仍然继续",
    
    "Open Workspace": "打开工作区",
    "Open in New Tab": "在新标签页中打开",
    "Open in New Window": "在新窗口中打开",
    "Open in Editor Window": "在编辑器窗口中打开",
    "Open Editor Window": "打开编辑器窗口",
    "Open as Editor": "作为编辑器打开",
    "Open as Pane": "作为面板打开",
    "Open Files": "打开文件",
    "Open in Web": "在浏览器中打开",
    "Open in Terminal Pane": "在终端面板中打开",
    "Open Composer Settings": "打开 Composer 设置",
    "Open Build Menu": "打开构建菜单",
    "Open environment.json": "打开 environment.json",
    "Open project config": "打开项目配置",
    
    "View diagram source": "查看图表源码",
    
    "Add to Project": "添加到项目",
    "Add to Home": "添加到主页",
    "Add to Team": "添加到团队",
    "Add to Eval": "添加到评估",
    "Add to Allowlist and Run": "添加到白名单并运行",
    
    "Copy Request ID": "复制请求 ID",
    "Copy Command": "复制命令",
    "Copy Current URL": "复制当前 URL",
    "Copy Domains": "复制域名",
    "Run Diagnostic": "运行诊断",
    "Network Diagnostics": "网络诊断",
    "Check network connectivity to all Cursor services": "检查与所有 Cursor 服务的网络连接",
    
    "Select Workspace": "选择工作区",
    "Select error type...": "选择错误类型...",
    "Select a repository": "选择代码仓库",
    "Give Feedback": "提供反馈",
    "Manage Billing": "管理账单",
    "Install Now": "立即安装",

    // ── 终端 ──
    
    "Compact Terminal Tool Calls": "紧凑显示终端工具调用",
    "Show terminal commands in compact view by default": "默认以紧凑视图显示终端命令",

    // ── 浏览器 ──
    "Take Screenshot": "截图",
    "Hard Reload": "强制刷新",
    "Clear Browsing History": "清除浏览记录",
    "Clear Cookies": "清除 Cookie",
    "Clear Cache": "清除缓存",
    "Clear Accepted Certificates": "清除已接受的证书",
    "Search or enter URL": "搜索或输入网址",
    "Can't connect to server": "无法连接到服务器",

    // ── 状态 & 错误 ──
    "Connection Failed": "连接失败",
    "Connection stalled": "连接中断",
    "An error occurred while processing your request.": "处理您的请求时发生错误。",
    "An unexpected error occurred. Reload the window to try again.": "发生意外错误。请重新加载窗口重试。",
    "Error: composerId is required": "错误：需要 composerId",
    "Failed to enqueue follow-up": "后续消息入队失败",
    "Submission blocked by hook": "提交被钩子阻止",
    "File reading blocked by hook": "文件读取被钩子阻止",
    "Workspace Not Found": "未找到工作区",
    "Incorrect Branch": "分支错误",
    "Usage Pricing Required": "需要设置用量计费",
    "Access Forbidden": "访问被拒绝",
    "Outdated Client": "客户端版本过旧",
    "You've hit rate limit for your Pro Plan": "您已达到专业版的使用限制",

    // ── 更新 ──
    "Check for Updates": "检查更新",
    "Checking for Updates": "正在检查更新",
    "Download Update": "下载更新",
    "Downloading Update": "正在下载更新",
    "Install Update": "安装更新",
    "Installing Update": "正在安装更新",
    "Restart to Update": "重启以更新",

    // ── 设置面板补充 ──
    "Auto-Run Network Access": "自动运行网络访问",
    "Allow network access": "允许网络访问",
    "Enable auto-keep": "启用自动保留",
    "Allow All": "允许所有",
    "Allow selected": "允许所选",
    "Always Apply": "始终应用",
    "Always Show Error": "始终显示错误",
    "Always applied": "始终应用",
    "Always ask": "始终询问",
    "Always run": "始终运行",
    "Apply Intelligently": "智能应用",
    "Apply Manually": "手动应用",
    "Apply changes locally": "在本地应用更改",
    "Apply to Specific Files": "应用于特定文件",
    "Apply to every chat and cmd-k session": "应用于每个对话和 Cmd+K 会话",
    "Applying changes locally": "正在本地应用更改",
    "Show Machine Label": "显示机器标签",
    "Show Sidebar": "显示侧边栏",
    "Hide Sidebar": "隐藏侧边栏",
    "Customize Sidebar": "自定义侧边栏",

    "Link Privacy": "链接隐私",
    "Help Improve Cursor": "帮助改进 Cursor",
    "Move to Local": "移至本地",
    "Save to Workspace": "保存到工作区",
    "Abort Agent and Restore Query": "中止智能体并恢复查询",
    "Abort Chat": "中止对话",
    "Abort the operation": "中止操作",
    "Accept Cursor Tab Suggestion": "接受 Cursor Tab 建议",
    "Accept Edits": "接受编辑",
    "Accept Mode Switch": "接受模式切换",
    "Accept Partial Edit": "接受部分编辑",
    
    "Accepted State": "已接受状态",
    "Actions Palette": "操作面板",
    "The best way to code with AI": "使用 AI 编程的最佳方式",
    "Resize changes sidebar": "调整更改侧边栏大小",
    "Approve Pending Shell Tool": "批准待处理的 Shell 工具",
    "Approve Pending Shell Tool and Allowlist": "批准待处理的 Shell 工具并加入白名单",
    "Approve this server": "批准此服务器",
    "Approve this tool": "批准此工具",
    "Add to allowlist": "添加到白名单",
    "Authenticating": "正在验证",
    "Finishing setup": "正在完成设置",
    "Workspace Diagnostics": "工作区诊断",
    "Reset to default": "恢复默认",
    "Skip this parameter": "跳过此参数",
    "Remember Preference": "记住偏好设置",
    "Argument": "参数",
    "Arguments": "参数",
    "Arguments to pass to the command": "传递给命令的参数",

    // ── 外观 & 主题 ──
    "Appearance": "外观",
    "Cursor Dark": "Cursor 深色",
    "Cursor Light": "Cursor 浅色",
    "Cursor Dark High Contrast": "Cursor 深色高对比度",

    // ── 新 Agents Window ──
    "New Agents Window (Glass)": "新建智能体窗口（Glass）",
    "Switch to Agents Window (Glass)": "切换到智能体窗口（Glass）",
    "Command Palette": "命令面板",

    // ── 代码库索引补充 ──
    "Index New Folders": "索引新文件夹",
    "Delete Index": "删除索引",
    "Crawl and index custom resources and developer docs": "爬取并索引自定义资源和开发者文档",

    // ── Diff & 编辑 ──
    "Load Diff": "加载差异",
    "Keep All": "保留全部",
    "Fix All": "修复全部",
    "Previous image": "上一张图片",
    "Next image": "下一张图片",
    "Undo Apply": "撤销应用",
    "Accept & Run": "接受并运行",

    // ── PR 相关 ──
    "Open in Prompt Quality": "在 Prompt Quality 中打开",
    "Open Prompt Quality": "打开 Prompt Quality",
    "Open Datadog Logs": "打开 Datadog 日志",
    "Open Request Logs": "打开请求日志",
    "Open Debug Directory": "打开调试目录",
    "Open in Datadog": "在 Datadog 中打开",
    "Capture Snapshot": "捕获快照",
    "Delete chat": "删除对话",
    "Download Video": "下载视频",
    "Copy Agent Deeplink": "复制智能体深度链接",

    // ── 插件 & 扩展 ──
    "Add Skills": "添加技能",
    "Add Path": "添加路径",
    "Add Port": "添加端口",
    
    "Add for Myself": "为自己添加",
    "Import from GitHub/GitLab": "从 GitHub/GitLab 导入",
    "Add plugins or import from GitHub to make them available for your team.": "添加插件或从 GitHub 导入，使团队成员可用。",
    "Add a custom MCP tool in your MCP config.": "在 MCP 配置中添加自定义 MCP 工具。",
    "Add a personal cloud MCP server to make it available to your cloud agents.": "添加个人云端 MCP 服务器，使其对云端智能体可用。",
    "Extend Cursor with Skills, Rules, Agents, Hooks, and MCPs": "使用技能、规则、智能体、钩子和 MCP 扩展 Cursor",
    "Include third-party Plugins, Skills, and other configs": "包含第三方插件、技能和其他配置",
    "Automatically import agent configs from other tools": "自动从其他工具导入智能体配置",

    // ── 权限 & 登录 ──

    "Access Settings": "访问设置",

    // ── 时间筛选 ──
    "Last 7 Days": "最近 7 天",
    "Last 30 Days": "最近 30 天",

    // ── 模式 ──
    "Ask Mode": "提问模式",

    // ── 其他高频 UI ──
    "About Cursor": "关于 Cursor",
    "Active workspace": "当前工作区",
    "Active workspace references": "当前工作区引用",
    "Add new stuff": "添加新内容",
    "Add or search model": "添加或搜索模型",
    "All Members": "所有成员",
    "All files and folders": "所有文件和文件夹",
    "All repos": "所有代码仓库",
    "All team members can access": "所有团队成员均可访问",
    "Anyone with the link can access": "拥有链接的人均可访问",
    "Are you sure you want to close this window?": "确定要关闭此窗口吗？",
    "Are you sure you want to perform this action?": "确定要执行此操作吗？",
    
    "No results found": "未找到结果",
    
    "Favorites, Recents": "收藏夹、最近使用",
    "Unread, Archived": "未读、已归档",

    // ── 设置面板补充（第二轮） ──
    "Files to include": "要包含的文件",
    "Files to exclude": "要排除的文件",
    "No files found": "未找到文件",
    "No matches found": "未找到匹配项",
    "Empty directory": "空目录",
    "No messages yet": "暂无消息",
    "No models found": "未找到模型",
    "No MCP servers": "暂无 MCP 服务器",
    "No plugins found": "未找到插件",
    "No skills available": "暂无可用技能",
    "No MCP resources available": "暂无可用的 MCP 资源",
    "No MCP Tools": "暂无 MCP 工具",
    "No No Rules Yet": "暂无规则",
    "Search MCP servers...": "搜索 MCP 服务器...",
    "Loading MCP servers...": "正在加载 MCP 服务器...",
    "Loading skills...": "正在加载技能...",
    "Search Plugins, Skills, Tools, Automations...": "搜索插件、技能、工具、自动化...",
    "Add skills, MCPs and more": "添加技能、MCP 等",
    "Browse MCPs": "浏览 MCP",
    "Manage plugins": "管理插件",
    "Plugin Settings": "插件设置",
    "Marketplace Settings": "插件市场设置",
    "Marketplace Access": "插件市场访问权限",
    "Select who can see and use plugins from this team marketplace": "选择谁可以查看和使用此团队插件市场中的插件",
    "Enable Auto Refresh": "启用自动刷新",
    "Automatically update plugins when changes are pushed to the repository": "当代码推送到仓库时自动更新插件",
    "Plugin Repository": "插件仓库",
    "Fetch marketplace plugins from the GitHub repository": "从 GitHub 仓库获取插件市场插件",
    "Available Marketplaces": "可用的插件市场",
    "Plugin Installation": "插件安装",
    "Verified by Cursor": "Cursor 已验证",
    "Manage Marketplace": "管理插件市场",
    "Delete marketplace?": "删除插件市场？",
    "This marketplace and its access settings will be removed. The repository won't be affected.": "此插件市场及其访问设置将被移除。源仓库不受影响。",
    "This marketplace and its access settings will be removed. The source repository won't be affected.": "此插件市场及其访问设置将被移除。源仓库不受影响。",
    "View changelog": "查看更新日志",
    "Changelog": "更新日志",
    "Report Issue": "报告问题",
    "Check Again": "重新检查",
    "Copy Error": "复制错误信息",
    "Debug Logs": "调试日志",
    "Clear Logs": "清除日志",
    "Try in Chat": "在对话中尝试",
    "Open in Chat": "在对话中打开",
    "Send to Chat": "发送到对话",
    "Ask follow-ups to the Cloud Agent...": "向云端智能体提问后续问题...",
    "Reproduction Steps": "复现步骤",
    "Tell us more (optional)...": "补充说明（可选）...",
    "Select error type...": "选择错误类型...",
    "Feature request": "功能请求",
    "Something is off": "有问题",
    "Urgent": "紧急",
    "Can't use Cursor": "无法使用 Cursor",
    "Uncommitted Changes": "未提交的更改",
    "You have uncommitted changes in your working tree. Choose an option, then continue.": "您的工作树中有未提交的更改。请选择一个选项后继续。",
    "Do not ask me again": "不要再问我",
    "Don't ask again": "不再询问",
    "Don't show again": "不再显示",
    "Stay on Current Branch": "留在当前分支",
    "No linked agents": "无关联的智能体",
    "Loading tasks...": "正在加载任务...",
    "No agents found": "未找到智能体",
    "Search Agents...": "搜索智能体...",
    "Select Backend": "选择后端",
    "Select Model": "选择模型",
    "Run in Cloud": "在云端运行",
    "Build Locally": "本地构建",
    "Build in Cloud": "在云端构建",
    "Send to Cloud": "发送到云端",
    "Run in Sandbox": "在沙箱中运行",
    "Thinking": "思考中",
    "Streaming text": "流式文本",
    "Tool executing": "工具执行中",
    "Summarizing": "总结中",
    "Reconnecting": "重新连接中",
    "Generating...": "生成中...",
    "Processing": "处理中",
    "Initializing": "初始化中",
    "Paused": "已暂停",
    "Stopped": "已停止",
    "Completed": "已完成",
    "In Progress": "进行中",
    "Waiting for upload...": "等待上传...",
    "Waiting for heartbeat": "等待心跳响应",
    "Waiting for logs": "等待日志",
    "Waiting for log entries...": "等待日志条目...",
    "Forking chat...": "正在分支对话...",
    "Forking...": "正在分支...",
    "Refreshing...": "正在刷新...",
    "Loading diff...": "正在加载差异...",
    "Loading Checks": "正在加载检查",
    "Loading plan...": "正在加载计划...",
    "Loading - Click": "加载中 - 点击",
    "Search or Paste Link": "搜索或粘贴链接",
    "Search files": "搜索文件",
    "Find in page": "在页面中查找",
    "Find in Terminal": "在终端中查找",
    "Find in File": "在文件中查找",
    "Find in Diff": "在差异中查找",
    "Find in Output": "在输出中查找",
    "Find in Changes": "在更改中查找",
    "Search in Files": "在文件中搜索",
    "Match case": "区分大小写",
    "Match whole word": "全词匹配",
    "Use regular expression": "使用正则表达式",
    "Replace all": "全部替换",
    "Replace all in file": "在文件中全部替换",
    "Clear search": "清除搜索",
    "Filter items...": "筛选项目...",
    "Searching...": "搜索中...",
    "Searching files": "正在搜索文件",
    "Select an option": "请选择一个选项",
    "Save to workspace": "保存到工作区",
    "New Automation": "新建自动化",
    "Create Chat": "创建对话",
    "Create Snapshot": "创建快照",
    "Create new canvas": "新建画布",
    "Create folder": "创建文件夹",
    "Create Pod": "创建 Pod",
    "Add folder": "添加文件夹",
    "Move to folder": "移动到文件夹",
    "Delete folder": "删除文件夹",
    "Delete file": "删除文件",
    "Delete Rule": "删除规则",
    "Delete Command": "删除命令",
    "Delete Skill": "删除技能",
    "Delete Subagent": "删除子智能体",
    "Delete chat": "删除对话",
    "Delete All Data": "删除所有数据",
    "Discard changes": "丢弃更改",
    "Discard All": "全部丢弃",
    "Undo All": "全部撤销",
    "Expand All": "全部展开",
    "Collapse All": "全部折叠",
    "Dismiss All": "全部忽略",
    "Mark All Read": "全部标为已读",
    "Mark All as Read": "全部标为已读",
    "Archive All": "全部归档",
    "Refresh All": "全部刷新",
    "Stop All": "全部停止",
    "Select all": "全选",
    "Deselect all": "取消全选",
    "No files": "无文件",
    "No changes": "无更改",
    "No description": "无描述",
    "No commits": "无提交",
    "No activity yet": "暂无活动",
    "No branches": "无分支",
    "No remote URL.": "无远程 URL。",
    "No result": "无结果",
    "No state": "无状态",
    "No linked agents": "无关联的智能体",
    "No agents found": "未找到智能体",
    "No agents yet": "暂无智能体",
    "No diagnostics found": "未找到诊断信息",
    "Diff View": "差异视图",
    "Unified": "统一视图",
    "Line Numbers": "行号",
    "Word Wrap": "自动换行",
    "Auto Save": "自动保存",
    "Keybindings": "快捷键绑定",
    "Editor Options": "编辑器选项",
    "Code Font Size": "代码字体大小",
    "UI Font Size": "界面字体大小",
    "UI Font Family": "界面字体族",
    "Code Font Family": "代码字体族",
    "Font Smoothing": "字体平滑",
    "Typography": "排版",
    "Manage Themes": "管理主题",
    "Select Theme...": "选择主题...",
    "Manage Themes...": "管理主题...",
    "High Contrast": "高对比度",
    "Changes Sidebar": "更改侧边栏",
    "Resize sidebar": "调整侧边栏大小",
    "Customize Sidebar": "自定义侧边栏",
    "Show Sidebar": "显示侧边栏",
    "Hide Sidebar": "隐藏侧边栏",
    "Show Panel": "显示面板",
    "Hide Panel": "隐藏面板",
    "Show Status Bar": "显示状态栏",
    "Hide Status Bar": "隐藏状态栏",
    "Show Terminal": "显示终端",
    "Hide Terminal": "隐藏终端",
    "Show History": "显示历史",
    "Show Output": "显示输出",
    "Show Changes": "显示更改",
    "Show More": "显示更多",
    "Show Less": "显示更少",
    "Worktrees": "工作树",
    "Max worktrees": "最大工作树数量",
    "Cleanup": "清理",
    "Active Line": "活动行",
    "Title Bar": "标题栏",
    "Breadcrumb": "面包屑导航",
    "Breadcrumbs": "面包屑导航",
    "Remote Host": "远程主机",
    "SSH Hostname": "SSH 主机名",
    "Forwarded Ports": "已转发的端口",
    "Port number": "端口号",
    "Submodule": "子模块",
    "Dev Containers": "开发容器",
    "Dev Container": "开发容器",
    "Connect Slack": "连接 Slack",
    "Connect SSH": "连接 SSH",
    "Connect WSL": "连接 WSL",
    "Connect via SSH": "通过 SSH 连接",
    "Connect via WSL": "通过 WSL 连接",
    "Set Up Workspace": "设置工作区",
    "Personal Usage": "个人用量",
    "On-Demand Usage": "按需用量",
    "Monthly Limit": "月度限额",
    "Plan & Usage": "计划与用量",
    "Limit Reached": "已达限额",
    "Upgrade to Pro": "升级到专业版",
    "Update Required": "需要更新",
    "Not Logged In": "未登录",
    "Login to Cursor": "登录 Cursor",
    "Log out?": "退出登录？",
    "Cursor Account": "Cursor 账号",
    "Open user config": "打开用户配置",
    "Open JSON": "打开 JSON",
    "Open Dashboard": "打开仪表板",
    "User MCP Servers": "用户 MCP 服务器",
    "Base URL": "基础 URL",
    "Deployment Name": "部署名称",
    "Enter model name": "输入模型名称",
    "Test Model": "测试模型",
    "OpenAI API Key": "OpenAI API 密钥",
    "Google API Key": "Google API 密钥",
    "AWS Bedrock": "AWS Bedrock",
    "Azure OpenAI": "Azure OpenAI",
    "AWS Access Key ID": "AWS 访问密钥 ID",
    "AWS Secret Access Key": "AWS 秘密访问密钥",
    "Access Key ID": "访问密钥 ID",
    "Secrets": "密钥",
    "OAuth Client ID (optional)": "OAuth 客户端 ID（可选）",
    "OAuth Client Secret (optional)": "OAuth 客户端密钥（可选）",
    "Large diffs are hidden by default.": "大型差异默认隐藏。",
    "Diff content not available": "差异内容不可用",
    "This file changed, but a text diff could not be rendered.": "此文件已更改，但无法渲染文本差异。",
    "Copy as Markdown": "复制为 Markdown",
    "Copy Code": "复制代码",
    "Copy File Path": "复制文件路径",
    "Copy Branch Name": "复制分支名称",
    "Copy Messages": "复制消息",
    "Copy prompt": "复制提示词",
    "Copy Image": "复制图片",
    "Download file": "下载文件",
    "Download image": "下载图片",
    "Download diagram": "下载图表",
    "Download Git": "下载 Git",
    "Screenshot": "截图",
    "Screenshot": "截图",
    "View fullscreen": "全屏查看",
    "Exit fullscreen": "退出全屏",
    "Live Preview": "实时预览",
    "Design Mode": "设计模式",
    "More Info": "更多信息",
    "More Options": "更多选项",
    "More actions": "更多操作",
    "Got it": "知道了",
    "Got it": "知道了",
    "Try again": "重试",
    "Try Again": "重试",
    "Maybe Later": "以后再说",
    "Skip For Now": "暂时跳过",
    "Continue Locally": "在本地继续",
    "Fixed": "已修复",
    "Copied": "已复制",
    "Importing": "导入中",
    "Editing": "编辑中",
    "Disconnected": "已断开连接",
    "Reconnect": "重新连接",
    "Forked": "已分支",
    "Archived": "已归档",
    "Installed": "已安装",
    "Imported": "已导入",
    "Pinned": "已固定",
    "Merged": "已合并",
    "Deleted": "已删除",
    "Renamed": "已重命名",
    "Changed Files": "已更改的文件",
    "Recent commits": "最近的提交",
    "All Commits": "所有提交",
    "Commit & Push": "提交并推送",
    "Commit on Main": "提交到主分支",
    "Current Branch": "当前分支",
    "Branch Name": "分支名称",
    "Branch Prefix": "分支前缀",
    "New Worktree": "新建工作树",
    "Checkout": "检出",
    "Squash merge": "压缩合并",
    "Squash & Merge": "压缩并合并",
    "Squash": "压缩",
    "Rebase": "变基",
    "Rebase Merge": "变基合并",
    "Create Draft PR": "创建草稿 PR",
    "Mark as Ready": "标记为就绪",
    "View PR": "查看 PR",
    "Open PR": "打开 PR",
    "Merge Method": "合并方式",
    "Code owner": "代码所有者",
    "Loading PR": "正在加载 PR",
    "Commits": "提交",
    "Reviews": "审查",
    "Unlink PR": "取消关联 PR",
    "Detail": "详情",
    "Plugin": "插件",
    "Verified": "已验证",
    "Available": "可用",
    "Required": "必需",
    "Remote": "远程",
    "Local Only": "仅本地",
    "Current": "当前",
    "Secondary": "次要",
    "Primary": "主要",
    "Group by": "分组依据",
    "Sort by": "排序依据",
    "Filter": "筛选",
    "Other...": "其他...",
    "Expand": "展开",
    "Collapse": "折叠",
    "Insert Snippet": "插入代码片段",
    "Go to Definition": "转到定义",
    "Find and Replace": "查找和替换",
    "Fix in Agent": "用智能体修复",
    "Fix with Agent": "用智能体修复",
    "Edit Selection": "编辑所选内容",
    "Quick Question": "快速提问",
    "Plan it out": "制定计划",
    "Debug component": "调试组件",
    "Multitask": "多任务",
    "Resubmit": "重新提交",
    "Open Agent": "打开智能体",
    "Open Agent by ID": "按 ID 打开智能体",
    "Next Agent": "下一个智能体",
    "Previous Agent": "上一个智能体",
    "New Cloud Agent": "新建云端智能体",
    "Plan Mode": "计划模式",
    "Debug Mode": "调试模式",
    "Multitask Mode": "多任务模式",
    "Cycle Mode": "循环模式",
    "Upgrade": "升级",
    "Popular!": "热门！",
    "Just now": "刚刚",
    "Remote": "远程",
    "Desktop": "桌面",
    "Recent": "最近",
    "Recents": "最近",
    "Details": "详情",
    "Other Agents": "其他智能体",
    "Results": "结果",
    "Errors": "错误",
    "Settings": "设置",
    "Gallery": "画廊",
    "Theme": "主题",
    "Customize": "自定义",

    // ── 设置面板补充（第三轮：从截图和 title/description 提取） ──
    "Move to Cloud to keep running longer without your computer open.": "移至云端以持续运行，无需保持电脑开启。",
    "Move to Cloud so the agent can keep running even if you disconnect.": "移至云端，即使断开连接智能体也能继续运行。",
    "Continue running in Cloud?": "在云端继续运行？",
    "Move this agent to the Cloud to run longer without your computer open.": "将此智能体移至云端，无需保持电脑开启即可长时间运行。",
    "Still running locally?": "仍在本地运行？",
    "Connection looks slow": "连接似乎较慢",
    "Close Running Tab?": "关闭正在运行的标签页？",
    "Reset Chat Mode to Default": "重置对话模式为默认",
    "Move into New Window": "移至新窗口",
    "Push local branch to remote": "将本地分支推送到远程",
    "Failed to push branch": "推送分支失败",
    "Failed to switch to Cloud Agent": "切换到云端智能体失败",
    "Cloud Agent requires code storage": "云端智能体需要代码存储",
    "Upgrade to use Cloud Agents": "升级以使用云端智能体",
    "Failed to retry Cloud Agent": "重试云端智能体失败",
    "Cloud Agents require a Git repo": "云端智能体需要 Git 仓库",
    "Git Not Initialized": "Git 未初始化",
    "No Git Remote": "无 Git 远程仓库",
    "Workspace Not at Git Root": "工作区不在 Git 根目录",
    "Cloud Agent Environment Required": "需要云端智能体环境",
    "Environment File Not Synced": "环境文件未同步",
    "Environment File Outdated": "环境文件已过期",
    "Reduce max chat tabs": "减少最大聊天标签页数",
    "Choose a folder for your new project": "为新项目选择文件夹",
    "Search Extensions": "搜索扩展",
    "Import VS Code Configuration": "导入 VS Code 配置",
    "Switch Privacy Mode?": "切换隐私模式？",
    "Failed to update privacy settings": "更新隐私设置失败",
    "Extension Security": "扩展安全性",
    "Configuration Errors": "配置错误",
    "Configure Ignored Files": "配置忽略的文件",
    "Delete Codebase Index?": "删除代码库索引？",
    "Local Automations": "本地自动化",
    "No local automations yet": "暂无本地自动化",
    "Loading local automations...": "正在加载本地自动化...",
    "Delete MCP Server": "删除 MCP 服务器",
    "Sign In to View Cloud MCP Servers": "登录以查看云端 MCP 服务器",
    "Could Not Load Cloud MCP Servers": "无法加载云端 MCP 服务器",
    "No User MCP Servers": "暂无用户 MCP 服务器",
    "Could Not Load Workspace MCP Servers": "无法加载工作区 MCP 服务器",
    "No User MCP Tools": "暂无用户 MCP 工具",
    "Plugin MCP Servers": "插件 MCP 服务器",
    "Discard all changes up to this checkpoint?": "丢弃此检查点之前的所有更改？",
    "Files changed outside of conversations": "在对话之外更改的文件",
    "Diff with Main Branch": "与主分支对比",
    "Commit on Main Branch": "在主分支上提交",
    "How did the agent do?": "智能体表现如何？",
    "Use in Agents Window": "在智能体窗口中使用",
    "Disable Inline Diffs": "禁用内联差异",
    "Checking out branch…": "正在切换分支…",
    "Incorrect Repository": "仓库错误",
    "Created by Cursor": "由 Cursor 创建",
    "Protected Configuration": "受保护的配置",
    "External File Protection": "外部文件保护",
    "Cloud Agents Unavailable": "云端智能体不可用",
    "Privacy Mode Enabled": "隐私模式已启用",
    "Select Custom Chime Sound": "选择自定义提示音",
    "Enable Run Everything?": "启用“运行所有”？",
    "Unsupported Model": "不支持的模型",
    "Transcript Link Copied": "对话链接已复制",
    "Bulk Import Chats \\u2014 pick directory of exported chats": "批量导入对话 — 选择导出的对话目录",
    "Show Chat History": "显示对话历史",
    "Chat history": "对话历史",
    "Add File to Cursor Chat": "添加文件到 Cursor 对话",
    "Add File to New Cursor Chat": "添加文件到新 Cursor 对话",
    "Add Directory to Cursor Chat": "添加目录到 Cursor 对话",
    "Add Directory to New Cursor Chat": "添加目录到新 Cursor 对话",
    "Browse Files": "浏览文件",
    "Nearby definitions": "附近的定义",
    "Code selections": "代码选择",
    "Download diagram as SVG": "下载图表为 SVG",
    "Download diagram as PNG": "下载图表为 PNG",
    "Download diagram as MMD": "下载图表为 MMD",
    "Copy table as CSV": "复制表格为 CSV",
    "Copy table as TSV": "复制表格为 TSV",
    "Download table as CSV": "下载表格为 CSV",
    "Download table as Markdown": "下载表格为 Markdown",
    "Reset zoom and pan": "重置缩放和平移",
    "Reset zoom to 100%": "重置缩放到 100%",
    "New Collection violated the Collection spec": "新集合违反了集合规范",
    "Move to Trash": "移到废纸篓",
    "Reveal in File Explorer": "在文件资源管理器中显示",
    "Reveal in Finder": "在 Finder 中显示",
    "Go to Next Change": "转到下一处更改",
    "Go to Previous Change": "转到上一处更改",
    "Bookmark This Page": "收藏此页面",
    "New Chat with Selections": "使用选区新建对话",
    "Switch to Model Slug": "切换到模型 Slug",
    "Select Default Profile": "选择默认配置文件",
    "Edit in File": "在文件中编辑",
    "Apply changes to the main working directory": "将更改应用到主工作目录",
    "No changes to review": "没有要审查的更改",
    "Resolve this merge conflict": "解决此合并冲突",
    "Copy sign in link": "复制登录链接",
    "Sign in link copied to clipboard": "登录链接已复制到剪贴板",
    "Request ID copied to clipboard": "请求 ID 已复制到剪贴板",
    "Switch between local changes and PRs": "在本地更改和 PR 之间切换",
    "Failed to load changes": "加载更改失败",
    "Select an item": "选择一个项目",
    "Add dark mode toggle to settings page": "在设置页面添加深色模式切换",
    "Implement theme persistence in localStorage": "在 localStorage 中实现主题持久化",
    "Add new doc": "添加新文档",
    "Add to Cursor": "添加到 Cursor",
    "Back to marketplace": "返回插件市场",
    "Try changing your search query": "尝试更改搜索关键词",
    "Failed to install plugin": "安装插件失败",
    "Failed to install marketplace plugin": "安装插件市场插件失败",
    "Recent commits - Select Repositories": "最近提交 - 选择仓库",
    "Recent commits - Select Commits": "最近提交 - 选择提交",
    "Connected" : "已连接",
    "Not authenticated": "未认证",
    "New Project": "新建项目",
    "Pull Request created": "拉取请求已创建",
    "VS Code extension marketplace with featured language extensions": "VS Code 扩展市场，包含精选语言扩展",
    "Set a spend limit to keep going.": "设置消费限额以继续使用。",
    "The amount needs to be a valid number": "金额必须为有效数字",
    "Planning next moves": "正在计划下一步",
    "Working on task": "正在处理任务",
    "Waiting for approval": "等待批准",
    "In progress": "进行中",
    "Verifying checksum": "正在验证校验值",
    "Copilot Edits": "Copilot 编辑",
    "Team Plugins cannot be uninstalled": "团队插件无法卸载",
    "Failed to process plugin installation": "处理插件安装失败",
    "Problem loading themes from marketplace": "从插件市场加载主题时出错",
    "Drag to adjust opacity": "拖动以调整透明度",
    "Drag to adjust stroke weight": "拖动以调整描边粗细",
    "Drag to adjust angle": "拖动以调整角度",
    "Name cannot be empty": "名称不能为空",

    // ── 输入框占位符 & 聊天提示 ──
    "Plan, Build, / for commands, @ for context": "计划、构建、/ 输入命令、@ 添加上下文",
    "Ask, learn, brainstorm": "提问、学习、头脑风暴",
    "Describe a project, feature, or long-term goal...": "描述一个项目、功能或长期目标...",
    "Plan, search, build anything": "计划、搜索、构建任何内容",
    "Add a follow-up": "添加后续消息",
    "Add more optional details": "添加更多可选详情",
    "Search files...": "搜索文件...",
    "Steer the plan, or add more details": "引导计划，或添加更多细节",
    "Select model": "选择模型",

    // ── 云端智能体补充 ──
    "Set up Cloud Agents": "设置云端智能体",
    "Plan New Idea": "计划新想法",
    "Background Agent": "后台智能体",
    "Continue executing this agent in the cloud.": "在云端继续执行此智能体。",
    "As a safety measure for our users, please login to use AI agents.": "为了用户安全，请登录后使用 AI 智能体。",
    "Please open a folder to use background agents.": "请打开一个文件夹以使用后台智能体。",
    "Please login to continue using Cursor.": "请登录以继续使用 Cursor。",
    "You are not logged in. Please log in to continue.": "您尚未登录。请登录后继续。",
    "Set up repository": "设置代码仓库",
    "Setting up repository": "正在设置代码仓库",
    "Setting up environment": "正在设置环境",
    "Starting environment setup": "正在启动环境设置",
    "Hydrated environment": "已恢复环境",
    "Loading environment": "正在加载环境",
    "Creating environment...": "正在创建环境...",
    "Completed setup": "设置完成",
    "Completed startup": "启动完成",
    "Completing setup": "正在完成设置",
    "Completing startup": "正在完成启动",
    "Starting up": "正在启动",
    "Waiting for VM to start...": "等待虚拟机启动...",
    "Waiting for artifact to upload": "等待产物上传",
    "Waiting for snapshot from another agent building this environment": "正在等待另一个构建此环境的智能体的快照",
    "Open a folder with a Git repository to use worktrees.": "打开包含 Git 仓库的文件夹以使用工作树。",
    "Worktree chats require a Git repository. Unable to check Git status for: ": "工作树对话需要 Git 仓库。无法检查 Git 状态：",

    // ── 状态消息 ──
    "Applied Locally": "已在本地应用",
    "Checking for changes...": "正在检查更改...",
    "Committing changes": "正在提交更改",
    "Discarding changes": "正在丢弃更改",
    "Stashing changes": "正在暂存更改",
    "Cloned repository": "已克隆代码仓库",
    "Cloning repository": "正在克隆代码仓库",
    "Building Docker image": "正在构建 Docker 镜像",
    "Built Docker image": "已构建 Docker 镜像",
    "Pulling Docker images": "正在拉取 Docker 镜像",
    "Pulled Docker images": "已拉取 Docker 镜像",
    "Loading PR status...": "正在加载 PR 状态...",
    "Merge status is being calculated...": "正在计算合并状态...",
    "Merging is blocked by branch protection rules": "合并被分支保护规则阻止",
    "Merge is blocked by a pre-receive hook": "合并被预接收钩子阻止",
    "Required status checks are failing": "必需的状态检查未通过",
    "This branch has conflicts that must be resolved": "此分支有必须解决的冲突",
    "This branch is behind the base branch and needs to be updated": "此分支落后于基础分支，需要更新",
    "This pull request cannot be merged": "此拉取请求无法合并",
    "This pull request is a draft": "此拉取请求是草稿",
    "Only the PR author can merge this pull request": "只有 PR 作者可以合并此拉取请求",
    "The merge commit cannot be cleanly created": "无法干净地创建合并提交",
    "Session expired": "会话已过期",
    "Updated successfully!": "更新成功！",
    "Created project at": "已创建项目于",
    "Created snapshot": "已创建快照",
    "Creating snapshot": "正在创建快照",
    "Created PRs": "已创建的 PR",
    "Committed & Pushed": "已提交并推送",
    "Started multitasking": "已开始多任务",
    "Started extensions": "已启动扩展",
    "Starting extensions": "正在启动扩展",
    "Extensions disabled": "扩展已禁用",
    "Installed extensions": "已安装的扩展",
    "Installing extensions": "正在安装扩展",
    "Taking longer than expected\\u2026": "耗时比预期更长…",
    "Running prepare script": "正在运行准备脚本",
    "Ran prepare script": "已运行准备脚本",
    "Running start script": "正在运行启动脚本",
    "Ran start script": "已运行启动脚本",
    "Running verify script": "正在运行验证脚本",
    "Ran verify script": "已运行验证脚本",
    "Ran verify script": "已运行验证脚本",

    // ── 操作确认 ──
    "Allow edits to external files": "允许编辑外部文件",
    "Confirm edit": "确认编辑",
    "Keep this edit?": "保留此编辑？",
    "Approve this plan?": "批准此计划？",
    "Continue locally": "在本地继续",
    "Run MCP tool?": "运行 MCP 工具？",
    "Reject, suggest, follow up?": "拒绝、建议还是追问？",
    "Rerun command?": "重新运行命令？",
    "Confirmation required for editing file outside workspace": "编辑工作区外的文件需要确认",
    "Ask for permission before running each operation": "每次运行操作前询问权限",
    "Automatically run all operations without asking for permission": "自动运行所有操作，无需询问权限",
    "Commands you approve once can run automatically when they match your allowlist.": "您批准一次的命令在与白名单匹配时可以自动运行。",
    "Allowlist MCP Tool": "将 MCP 工具加入白名单",
    "Run MCP tool": "运行 MCP 工具",
    "Run outside sandbox:": "在沙箱外运行：",
    "Run with network:": "联网运行：",
    "Awaiting approval": "等待批准",
    "Awaiting edit approval": "等待编辑批准",
    "Awaiting plan review": "等待计划审查",
    "Awaiting terminal approval": "等待终端批准",
    "Awaiting MCP tool approval": "等待 MCP 工具批准",
    "MCP authentication timed out. Please try again.": "MCP 认证超时。请重试。",
    "You are not authorized to complete this MCP authentication flow.": "您无权完成此 MCP 认证流程。",
    "No sandbox: full filesystem and network access.": "无沙箱：完整的文件系统和网络访问。",
    "Sandbox: only fetches from domains in your allowlist": "沙箱：仅从白名单中的域名获取",

    // ── 用量 & 升级 ──
    "Usage limit reached": "已达用量限制",
    "Total usage limit reached": "已达总用量限制",
    "Upgrade for 3x usage & faster responses": "升级以获得 3 倍用量和更快响应",
    "Upgrade for 20x usage & faster responses": "升级以获得 20 倍用量和更快响应",
    "Upgrade for extended usage & faster responses": "升级以获得扩展用量和更快响应",
    "Upgrade to Pro+": "升级到 Pro+",
    "Upgrade to Ultra": "升级到 Ultra",
    "Get faster responses": "获得更快响应",
    "You've reached your Free plan limit. Upgrade to Pro for expanded agent usage.": "您已达到免费版限制。升级到专业版以扩展智能体使用。",
    "You've reached your monthly limit. Set a new on-demand limit to continue.": "您已达到月度限制。设置新的按需限制以继续。",
    "You've reached your team's usage limit.": "您已达到团队用量限制。",
    "You've reached your usage limit.": "您已达到用量限制。",
    "Get 3x more usage than Pro, unlock higher limits on Agent, and more.": "获得专业版 3 倍用量，解锁更高的智能体限制等。",
    "Get maximum value with 20x usage limits and early access to advanced features.": "获得 20 倍用量限制和高级功能的抢先体验，实现最大价值。",
    "Without the pro plan, you do not have access to this feature/model.": "没有专业版计划，您无法使用此功能/模型。",
    "By default, Cursor learns from code to help you get the best experience possible.": "默认情况下，Cursor 从代码中学习以帮助您获得最佳体验。",
    "Set a new limit": "设置新限制",
    "Payment failed": "付款失败",
    "Plan ending soon": "计划即将到期",
    "Review Plan": "审查计划",

    // ── MCP / 工具 / 插件 ──
    "Enable web search capability": "启用网络搜索功能",
    "Generate image": "生成图片",
    "Generated image": "已生成图片",
    "Image generation cancelled": "图片生成已取消",
    "Image generation failed": "图片生成失败",
    "Image generation rejected": "图片生成被拒绝",
    "Image generation skipped": "图片生成已跳过",
    "Cursor Settings": "Cursor 设置",
    "Cursor Cloud": "Cursor 云端",
    "Cursor Rule": "Cursor 规则",
    "Cursor Blame": "Cursor 追溯",
    "Close Settings": "关闭设置",
    "Close Window": "关闭窗口",
    "Open Marketplace": "打开插件市场",
    "Open Browser Tab": "打开浏览器标签页",
    "Switch Theme": "切换主题",
    "Update Cursor": "更新 Cursor",
    "Quit Cursor?": "退出 Cursor？",
    "Configure Azure OpenAI to use OpenAI models through your Azure account.": "配置 Azure OpenAI 以通过您的 Azure 账户使用 OpenAI 模型。",
    "Fix all in Cursor": "在 Cursor 中全部修复",
    "Fix in Cursor": "在 Cursor 中修复",
    "Fixed Merge Conflicts": "已解决合并冲突",
    "No changes to create PR": "没有可创建 PR 的更改",
    "No staged changes": "没有已暂存的更改",
    "No unstaged changes": "没有未暂存的更改",
    "Changes from current branch to main branch": "从当前分支到主分支的更改",
    "Current changes in the repository": "代码仓库中的当前更改",
    "Couldn't create project at": "无法创建项目于",
    "Couldn't open": "无法打开",
    "Name is required.": "名称为必填项。",
    "Prompt is required.": "提示词为必填项。",
    "Share ID cannot be empty": "分享 ID 不能为空",
    "This parameter is required": "此参数为必填项",
    "Enter a valid 5-field cron expression.": "请输入有效的 5 字段 cron 表达式。",
    "Please enter a valid integer": "请输入有效的整数",
    "Please enter a valid number": "请输入有效的数字",
    "No parameters found": "未找到参数",
    "Command execution timed out": "命令执行超时",
    "Task does not define a command.": "任务未定义命令。",
    "Task uses unsupported VS Code variables.": "任务使用了不支持的 VS Code 变量。",
    "An unspecified error occurred. Please try again": "发生未指定的错误。请重试",
    "The provided API key is invalid. Please provide a valid API key.": "提供的 API 密钥无效。请提供有效的 API 密钥。",
    "File is being edited by another chat": "文件正在被其他对话编辑",
    "Workspace not trusted": "工作区未受信任",
    "Open in Cursor": "在 Cursor 中打开",
    "Add to Cursor": "添加到 Cursor",
    "Allow edits to external files": "允许编辑外部文件",
    "Spin up a new thread with this plan as context": "以此计划为上下文启动新线程",
    "Create detailed plans for accomplishing tasks": "创建完成任务的详细计划",
    "Create structured plans with implementation steps": "创建包含实现步骤的结构化计划",
    "Coordinate long-horizon tasks with delegated subagents": "通过委派子智能体协调长期任务",
    "Editing queued message...": "正在编辑排队中的消息...",
    "Queued Message": "排队中的消息",

    // ── 工作树页面 ──
    "Cursor periodically removes old worktrees to free disk space. Tune how aggressively cleanup runs.": "Cursor 会定期移除旧的工作树以释放磁盘空间。调整清理的激进程度。",
    "Maximum number of Cursor-managed worktrees to retain across all workspaces. Older worktrees are removed first.": "跨所有工作区保留的 Cursor 管理工作树最大数量。优先移除较旧的工作树。",
    "Max total size (GB)": "最大总大小 (GB)",
    "Maximum total size in GB across all Cursor-managed worktrees. Set to 0 to disable the size limit.": "所有 Cursor 管理的工作树的最大总大小（GB）。设为 0 可禁用大小限制。",
    "No Cursor-managed worktrees on this machine.": "此机器上没有 Cursor 管理的工作树。",

    // ── Models 页面 ──
    "Override OpenAI Base URL": "覆盖 OpenAI 基础 URL",
    "Change the base URL for OpenAI API requests.": "更改 OpenAI API 请求的基础 URL。",
    "Configure AWS Bedrock to use Anthropic Claude models through your AWS account. Cursor Enterprise teams can configure IAM roles to access Bedrock without any Access Keys.": "配置 AWS Bedrock 以通过 AWS 账户使用 Anthropic Claude 模型。Cursor 企业团队可配置 IAM 角色以在无需访问密钥的情况下访问 Bedrock。",
    "API Keys": "API 密钥",

    // ── 智能体页面补充 ──
    "Allow Agent to switch modes without asking first, such as Agent to Plan or Agent to Debug. When off, Cursor asks before switching.": "允许智能体在未询问的情况下切换模式，例如从智能体切换到计划或调试模式。关闭后，Cursor 会在切换前询问。",
    "Explore subagent": "探索子智能体",
    "The Explore subagent is used to do initial research for the main agent": "探索子智能体用于为主智能体进行初步研究",
    "Tools will auto-run in a sandbox if possible. If not, they will respect the allowlist or ask for approval.": "工具将尽可能在沙箱中自动运行。否则将遵循白名单或请求批准。",
    "Control which network requests are allowed when commands run in the sandbox. Edit allowed/denied domains in sandbox.json in your workspace.": "控制命令在沙箱中运行时允许的网络请求。在工作区的 sandbox.json 中编辑允许/拒绝的域名。",
    "Prefix for new branches created by Agent (e.g., cursor/, username/)": "智能体创建的新分支前缀（例如 cursor/、username/）",

    // ── 外观/主题页面 ──
    "Choose between light, dark, or high contrast themes": "在浅色、深色或高对比度主题之间选择",
    "Choose a tint color": "选择色调颜色",
    "Control how strongly the tint is applied": "控制色调应用的强度",
    "Reduce Transparency": "减少透明度",
    "Replace translucent surfaces with opaque backgrounds": "用不透明背景替换半透明表面",
    "Font size for the Cursor user interface": "Cursor 用户界面的字体大小",
    "Font size for code editors and diffs": "代码编辑器和差异视图的字体大小",
    "Override the Cursor user interface typeface": "覆盖 Cursor 用户界面的字体",
    "Override the font for code editors and diffs": "覆盖代码编辑器和差异视图的字体",
    "Use native macOS font anti-aliasing": "使用 macOS 原生字体抗锯齿",
    "Hide Email Address": "隐藏邮箱地址",
    "Partially mask your email address in the Cursor user interface": "在 Cursor 用户界面中部分遮挡您的邮箱地址",

    // ── 通用页面补充 ──
    "Warning Notifications": "警告通知",
    "Show warning-level in-app toasts": "显示应用内的警告级别提示",
    "Menu Bar Icon": "菜单栏图标",
    "Show Cursor in menu bar": "在菜单栏显示 Cursor",

    // ── 侧边栏标签修复 ──
    "Indexing": "索引",
    "Docs": "文档",
    "Terminals": "终端",
    "Hue": "色调",
    "Intensity": "强度",
    "Colors": "颜色"
};

const riskyShortWords = {
    "General": "通用",
    "Agents": "智能体",
    "Tab": "Tab 补全",
    "Models": "模型",
    "Plugins": "插件",
    "Hooks": "钩子",
    "Network": "网络",
    "Beta": "测试功能",
    "Marketplace": "插件市场",
    "Docs": "官方文档",
    "Open": "打开",
    "Invite": "邀请",
    "Import": "导入",
    "Show": "显示",
    "Auto-Run": "自动运行",
    "Pane": "面板",
    "Small": "小",
    "Default": "默认",
    "Large": "大",
    "Imports": "导入",
    "Rules": "规则",
    "Skills": "技能",
    "Subagents": "子智能体",
    "Commands": "命令",
    "Unlimited": "无限制",
    "Custom": "自定义",
    "Auto": "自动",
    "Always": "始终",
    "Never": "从不",
    "Quick": "快速",
    "Deep": "深度",
    "Context": "上下文",
    "Log Out": "退出登录",
    "Open Folder": "打开文件夹",
    "Browse Marketplace": "浏览插件市场",
    "Suggested": "推荐",
    "Copy Domains": "复制域名",
    "Run Diagnostic": "运行诊断",
    "Development": "开发",
    "Early Access": "抢先体验",
    "Nightly": "Nightly",
    "Configured Hooks": "已配置的钩子",
    "Execution Log": "执行日志",
    "Clear log": "清空日志",
    "Tools": "工具",
    "Browser": "浏览器",
    "Installed MCP Servers": "已安装的 MCP 服务器",
    "Off": "关闭",
    "Browser Tab": "浏览器标签页",
    "Cancel": "取消",
    "Confirm": "确认",
    "Hide": "隐藏",
    "Edit": "编辑",

    // ── 新增安全短词（仅多词短语或 Cursor 特有术语，避免单字通用词） ──
    "Log In": "登录",
    "Sign Up": "注册",
    "Stop All": "全部停止",
    "New Tab": "新标签页",
    "New Chat": "新对话",
    "New Terminal": "新建终端",
    "Cloud Agent": "云端智能体",
    "New Agent": "新建智能体",
    "Add to Chat": "添加到对话",
    "View Details": "查看详情",
    "Close Tab": "关闭标签页",
    "Learn More": "了解更多",
    "Get Started": "开始使用",
    "Close Chat": "关闭对话",
    "Open Folder": "打开文件夹",
    "New Window": "新窗口",
    "Open Settings": "打开设置",
    "Add Folder": "添加文件夹",
    "Accept Suggestion": "接受建议",
    "Data Sharing": "数据共享",
    "Share Data": "共享数据",
    "Copy link": "复制链接",
    "Get Started": "开始使用",
    "MCP Servers": "MCP 服务器",
    "MCPs": "MCP",
    "Cmd+K": "Cmd+K",
    "Select All": "全选",
    "Get Started": "开始使用",
    "Manage Themes": "管理主题",
    "Cursor Account": "Cursor 账号",
    "Upgrade to Pro": "升级到专业版",
    "Log In": "登录",
    "Sign Up": "注册",
    "Plan Mode": "计划模式",
    "Live Preview": "实时预览",
    "Design Mode": "设计模式",
    "New Browser": "新建浏览器",
    "New File": "新建文件",
    "Open File": "打开文件",
    "Save File": "保存文件",
    "Recent": "最近",
    "Recents": "最近",
    "Gallery": "画廊"
};

module.exports = { safeGlobalDict, riskyShortWords };
